(categoria,     url_categoria,        subcategoria,     url_subcategoria, subcategoria2, url_subcategoria2, subcategoria3, url_subcategoria3, subcategoria4, url_subcategoria4)
('Jardín', 'productos/jardin.html', 'Arrollamangueras', 'productos/arrollamangueras.html', None, None, None, None, None, None),
('Jardín', 'productos/jardin.html', 'Bebederos', 'productos/bebederos.html', None, None, None, None, None, None),
('Jardín', 'productos/jardin.html', 'Llamadores', 'productos/llamadores.html', None, None, None, None, None, None),
('Jardín', 'productos/jardin.html', 'Veletas', 'productos/veletas.html', None, None, None, None, None, None),
('Jardín', 'productos/jardin.html', 'Muebles de Jardín', 'productos/muebles-de-jardin.html', 'Función de hierro', 'productos/funcion-de-hierro.html', None, None, None, None),
('Jardín', 'productos/jardin.html', 'Muebles de Jardín', 'productos/muebles-de-jardin.html', 'Fundición de aluminio', 'productos/fundicion-de-aluminio.html', None, None, None, None),
('Jardín', 'productos/jardin.html', 'Muebles de Jardín', 'productos/muebles-de-jardin.html', 'Hierro forjado', 'productos/hierro-forjado.html', None, None, None, None),
('Parrillas', 'productos/parrillas.html', 'Accesorios para parrillas', 'productos/accesorios-para-parrillas.html', None, None, None, None, None, None),
('Parrillas', 'productos/parrillas.html', 'Asadores', 'productos/asadores.html', None, None, None, None, None, None),
('Parrillas', 'productos/parrillas.html', 'Herrajes', 'productos/herrajes.html', None, None, None, None, None, None),
('Parrillas', 'productos/parrillas.html', 'Parrillas a carbón o leña', 'productos/parrillas-a-carbon-o-lena.html', None, None, None, None, None, None),
('Parrillas', 'productos/parrillas.html', 'Parrillas a gas', 'productos/parrillas-a-gas.html', None, None, None, None, None, None),
('Calefacción', 'productos/calefaccion.html', 'Hogares', 'productos/hogares.html', None, None, None, None, None, None),
('Iluminación', 'productos/iluminacion.html', 'Faroles', 'productos/faroles.html', None, None, None, None, None, None),
('Iluminación', 'productos/iluminacion.html', 'Faroles con columnas', 'productos/faroles-con-columnas.html', None, None, None, None, None, None),
('Gastronomía', 'productos/gastronomia.html', 'Calderos en hierro', 'productos/calderos-en-hierro.html', None, None, None, None, None, None),
('Gastronomía', 'productos/gastronomia.html', 'Calcerolas de fundicion', 'productos/cacerolas-de-fundicion.html', 'Enlonzadas', 'productos/cacerolas-de-fundicion-enlonzadas.html', None, None, None, None),
('Gastronomía', 'productos/gastronomia.html', 'Calcerolas de fundicion', 'productos/cacerolas-de-fundicion.html', 'Sin enlonzar', 'productos/cacerolas-de-fundicion-sin-enlonzar.html', 'Ovaladas', 'productos/cacerolas-de-fundicion-sin-enlonzar-ovaladas.html', 'Doble función', 'productos/cacerolas-de-fundicion-sin-enlonzar-ovaladas-doble-funcion.html'),
('Gastronomía', 'productos/gastronomia.html', 'Planchas para bifes', 'productos/planchas-para-bifes.html', 'Lisas', 'productos/planchas-para-bifes-lisas.html', None, None, None, None),
('Gastronomía', 'productos/gastronomia.html', 'Planchas para bifes', 'productos/planchas-para-bifes.html', 'Rayadas', 'productos/planchas-para-bifes-rayadas.html', 'Enlonzadas', 'productos/planchas-para-bifes-rayadas-enlozadas.html', None, None),
('Gastronomía', 'productos/gastronomia.html', 'Planchas para bifes', 'productos/planchas-para-bifes.html', 'Rayadas', 'productos/planchas-para-bifes-rayadas.html', 'Sin enlonzar', 'productos/planchas-para-bifes-rayadas-sin-enlozar.html', None, None),
('Gastronomía', 'productos/gastronomia.html', 'Provoleteras de fundicion', 'productos/provoleteras.html', 'De 15 porciones', 'productos/provoleteras-15-porciones.html', 'Enlonzadas', 'productos/provoleteras-15-porciones-enlozadas.html', None, None),
('Gastronomía', 'productos/gastronomia.html', 'Provoleteras de fundicion', 'productos/provoleteras.html', 'De 15 porciones', 'productos/provoleteras-15-porciones.html', 'Sin enlonzar', 'productos/provoleteras-15-porciones-sin-enlonzar.html', None, None),
('Gastronomía', 'productos/gastronomia.html', 'Provoleteras de fundicion', 'productos/provoleteras.html', 'Mangos de fundicion', 'productos/provoleteras-mango-de-fundicion.html', 'Enlonzadas', 'productos/provoleteras-enlonzadas.html', None, None),
('Gastronomía', 'productos/gastronomia.html', 'Provoleteras de fundicion', 'productos/provoleteras.html', 'Mangos de fundicion', 'productos/provoleteras-mango-de-fundicion.html', 'Sin enlonzar', 'productos/provoleteras-sin-enlonzar.html', None, None),
('Gastronomía', 'productos/gastronomia.html', 'Provoleteras de fundicion', 'productos/provoleteras.html', 'Mangos de madera', 'productos/provoleteras-mango-de-madera.html', 'Enlonzadas', 'productos/provoleteras-enlonzadas.html', None, None),
('Gastronomía', 'productos/gastronomia.html', 'Provoleteras de fundicion', 'productos/provoleteras.html', 'Mangos de madera', 'productos/provoleteras-mango-de-madera.html', 'Sin enlonzar', 'productos/provoleteras-sin-enlonzar.html', None, None),
('Gastronomía', 'productos/gastronomia.html', 'Asaderas en chapa plegada', 'productos/asaderas-en-chapa-plegada.html', None, None, None, None, None, None),
('Gastronomía', 'productos/gastronomia.html', 'Paelleras con 2 asas', 'productos/paelleras-con-2-asas.html', 'Enlonzadas', 'productos/paelleras-con-2-asas-enlozadas.html', None, None, None, None),
('Gastronomía', 'productos/gastronomia.html', 'Paelleras con 2 asas', 'productos/paelleras-con-2-asas.html', 'Sin enlonzar', 'productos/paelleras-con-2-asas-sin-enlonzar.html', None, None, None, None),
('Gastronomía', 'productos/gastronomia.html', 'Woks', 'productos/woks.html', 'Enlonzados', 'productos/woks-enlozados.html', None, None, None, None),
('Gastronomía', 'productos/gastronomia.html', 'Woks', 'productos/woks.html', 'Sin enlonzar', 'productos/woks-sin-enlonzar.html', None, None, None, None),
('Gastronomía', 'productos/gastronomia.html', 'Pizzera en chapa enlozada', 'productos/pizzera-en-chapa-enlozada.html', None, None, None, None, None, None)